spring.application.name=demo

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Todo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hikari Connection Pool
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# Hibernate / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# Jackson
# ===============================
spring.jackson.serialization.indent-output=true

# ===============================
# DevTools
# ===============================
spring.devtools.restart.enabled=true

# ===============================
# Error
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always

# ===============================
# Debug
# ===============================
debug=false